### PR TITLE
Rx development 202002.00 elasticsearch

### PR DESCRIPTION
**Pull request by AtsushiFujioka**
Completed development for Elasticsearch
-----------

Checklist:
----------

- [x] I have tested my changes. No regression in existing tests.
- [x] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by VanNamDinh — CHANGES_REQUESTED** [review]
Please revert #define APP_VERSION_BUILD 3 to default

**Review by VanNamDinh — CHANGES_REQUESTED** [review]
#65

**Review by VanNamDinh — APPROVED** [review]
Ok!!!!

**Comment by HirokiIshiguro** [comment]
thank you @AtsushiFujioka , @VanNamDinh

**Pull request merged**
