### PR TITLE
[RX72N EnvisionKit] Added MQTT demo project

### PR DESCRIPTION
**Pull request by Wolveries**
[RX72N EnvisionKit Demo]

Description
-----------
Added MQTT demo project.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by VanNamDinh — CHANGES_REQUESTED** [review]
Hi@resg-xuan, @Wolveries 

Why did you remove #include <stdio.h> on aws_iot_ota_mqtt.c?
Please remove .settings and src/gen folders from aws_tests

image

**Comment by Wolveries** [comment]
> Hi@resg-xuan, @Wolveries
> 
> Why did you remove #include <stdio.h> on aws_iot_ota_mqtt.c?
> Please remove .settings and src/gen folders from aws_tests
> 
> image

Hi @VanNamDinh,
Cc @resg-xuan,

The commit to add "#include <stdio.h>" causes IDT FreeRTOSIntegrity failed. The file "aws_iot_ota_mqtt.c" is not recommended to change. Then I reverse that commit.

I will remove .settings and src/gen from aws_tests.

**Comment by VanNamDinh** [comment]
Hi @Wolveries,

Ok. I see. But if you remove #include <stdio.h>, the OTA demo on RX65N and Cloud Kit can not work.


cc: @HirokiIshiguro,

Do you have any ideas? Should we keep or remove #include <stdio.h> ?

**Comment by HirokiIshiguro** [comment]
> Do you have any ideas? Should we keep or remove #include <stdio.h> ?

Thank you for your developing @resg-xuan @Wolveries @VanNamDinh 

I prefer "keep"  for good behavior on actual RX MCUs boards. It is OK if we would face error on IDT test logs.
I think we can explain this IDT error to AWS when we would advance to AWS certification phase.

**Comment by VanNamDinh** [comment]
> > Hi@resg-xuan, @Wolveries
> > Why did you remove #include <stdio.h> on aws_iot_ota_mqtt.c?
> > Please remove .settings and src/gen folders from aws_tests
> > image
> 
> Hi @VanNamDinh,
> Cc @resg-xuan,
> 
> The commit to add "#include <stdio.h>" causes IDT FreeRTOSIntegrity failed. The file "aws_iot_ota_mqtt.c" is not recommended to change. Then I reverse that commit.
> 
> I will remove .settings and src/gen from aws_tests.

Hi @Wolveries,
We want to keep it, please revert and re-submit PR again. I will check on weekend.

**Comment by Wolveries** [comment]
> > Do you have any ideas? Should we keep or remove #include <stdio.h> ?
> 
> Thank you for your developing @resg-xuan @Wolveries @VanNamDinh
> 
> I prefer "keep" for good behavior on actual RX MCUs boards. It is OK if we would face error on IDT test logs.
> I think we can explain this IDT error to AWS when we would advance to AWS certification phase.

Hi @HirokiIshiguro,

Can we try to include the header file in another place to avoid FreeRTOSIntegrity failed? Is it possible?

**Comment by HirokiIshiguro** [comment]
> Hi @HirokiIshiguro,
> 
> Can we try to include the header file in another place to avoid FreeRTOSIntegrity failed? Is it possible?

@Wolveries  Yes, this is good idea. thank you.

**Comment by Wolveries** [comment]
> > Hi @HirokiIshiguro,
> > Can we try to include the header file in another place to avoid FreeRTOSIntegrity failed? Is it possible?
> 
> @Wolveries Yes, this is good idea. thank you.

Hi @VanNamDinh,

Could you try to put "#include <stdio.h>" to another place (after reviewing my commit for RX72N Envision Kit) as @HirokiIshiguro's comment? I have a look at OTA demo for RX65N Cloud Kit, but it includes many linked resources to local environment. I suggest to use environment variable instead of absolute path.

**Comment by VanNamDinh** [comment]
> #include <stdio.h>

@Wolveries ,
Thanks for your PR, I will merge you PR and put #include <stdio.h> to somewhere.

**Pull request merged**
